### ISSUE TITLE
Meta data is no longer saved

### ISSUE THREAD

**Issue by remcotolsma** [pronamic/wp-pronamic-persons#1]
_Internal HelpScout ticket: https://secure.helpscout.net/conversation/2124454926/25061?folderId=1425710_

**Comment by remcotolsma** [comment]
**Before:**

https://github.com/pronamic/wp-pronamic-persons/blob/977e873be7fcb7c07cce478545364476e7b284b8/includes/meta-boxes.php#L119-L121

**After:**

https://github.com/pronamic/wp-pronamic-persons/blob/caae5d677637ee0d896a10c6124f9ec36c2422d3/includes/meta-boxes.php#L119-L121

CC @kjtolsma  @rvdsteege 

> `current_user_can( 'edit_post' )` is nooit juist geweest, het is `current_user_can( 'edit_posts' )`  of `current_user_can( 'edit_post', $post_id )`. Maar kwam dit recent ook ergens anders tegen (weet zo even niet meer waar), dus misschien is er wel iets gewijzigd ja.

I can imagine that this is also set up incorrectly in other custom plugins.

**Comment by rvdsteege** [comment]
> I can imagine that this is also set up incorrectly in other custom plugins.

https://github.com/search?q=org%3Apronamic%20%22current_user_can(%20%27edit_post%27%20)%22&type=code
